"use server"

import { createClient } from "@/lib/supabase/server"
import { sendEmail } from "@/lib/aws-ses"

export async function sendROIReport(formData: FormData) {
  const email = formData.get("email") as string
  const reportData = formData.get("reportData") as string

  if (!email || !reportData) {
    return { success: false, message: "Missing required fields" }
  }

  const parsedData = JSON.parse(reportData)

  const htmlContent = `
    <html>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #333;">Your ROI Analysis Report</h1>
        <p>Thank you for using our ROI Calculator. Here are your results:</p>
        
        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h2 style="color: #0066cc;">Current State</h2>
          <p><strong>Annual Revenue:</strong> $${parsedData.annualRevenue.toLocaleString()}</p>
          <p><strong>Current DSO:</strong> ${parsedData.currentDSO} days</p>
          <p><strong>Bad Debt Rate:</strong> ${parsedData.badDebtRate}%</p>
        </div>

        <div style="background: #e8f4f8; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h2 style="color: #0066cc;">Projected Results</h2>
          <p><strong>Improved DSO:</strong> ${parsedData.projectedDSO} days</p>
          <p><strong>Annual Savings:</strong> $${parsedData.annualSavings.toLocaleString()}</p>
          <p><strong>Cash Flow Improvement:</strong> $${parsedData.cashFlowImprovement.toLocaleString()}</p>
        </div>

        <p style="margin-top: 30px;">Ready to achieve these results? <a href="${process.env.NEXT_PUBLIC_SITE_URL}/demo" style="color: #0066cc;">Schedule a demo</a> to see how Kuhlekt can transform your receivables management.</p>
        
        <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;" />
        <p style="color: #666; font-size: 12px;">This report was generated by Kuhlekt ROI Calculator</p>
      </body>
    </html>
  `

  const textContent = `
Your ROI Analysis Report

Thank you for using our ROI Calculator. Here are your results:

Current State:
- Annual Revenue: $${parsedData.annualRevenue.toLocaleString()}
- Current DSO: ${parsedData.currentDSO} days
- Bad Debt Rate: ${parsedData.badDebtRate}%

Projected Results:
- Improved DSO: ${parsedData.projectedDSO} days
- Annual Savings: $${parsedData.annualSavings.toLocaleString()}
- Cash Flow Improvement: $${parsedData.cashFlowImprovement.toLocaleString()}

Ready to achieve these results? Visit ${process.env.NEXT_PUBLIC_SITE_URL}/demo to schedule a demo.
  `

  const result = await sendEmail({
    to: email,
    subject: "Your Kuhlekt ROI Analysis Report",
    text: textContent,
    html: htmlContent,
  })

  return result
}

export async function generateVerificationCode(email: string) {
  const code = Math.floor(100000 + Math.random() * 900000).toString()
  const expiresAt = new Date(Date.now() + 10 * 60 * 1000)

  try {
    const supabase = await createClient()

    const { error: deleteError } = await supabase.from("verification_codes").delete().eq("email", email)

    if (deleteError) {
      console.error("Error deleting old codes:", deleteError)
    }

    const { error: insertError } = await supabase.from("verification_codes").insert({
      email,
      code,
      expires_at: expiresAt.toISOString(),
      attempts: 0,
    })

    if (insertError) {
      console.error("Error inserting verification code:", insertError)
      return { success: false, message: "Failed to generate verification code" }
    }

    const htmlContent = `
      <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #333;">Your Verification Code</h1>
          <p>Your verification code for the ROI Calculator is:</p>
          <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0;">
            <h2 style="color: #0066cc; font-size: 36px; letter-spacing: 8px;">${code}</h2>
          </div>
          <p>This code will expire in 10 minutes.</p>
          <p style="color: #666; font-size: 12px;">If you didn't request this code, please ignore this email.</p>
        </body>
      </html>
    `

    const textContent = `
Your Verification Code

Your verification code for the ROI Calculator is: ${code}

This code will expire in 10 minutes.

If you didn't request this code, please ignore this email.
    `

    const emailResult = await sendEmail({
      to: email,
      subject: "Your Kuhlekt Verification Code",
      text: textContent,
      html: htmlContent,
    })

    return emailResult
  } catch (error) {
    console.error("Error in generateVerificationCode:", error)
    return { success: false, message: "Failed to generate verification code" }
  }
}

export async function verifyCode(email: string, code: string) {
  try {
    const supabase = await createClient()

    const { data, error } = await supabase
      .from("verification_codes")
      .select("*")
      .eq("email", email)
      .eq("code", code)
      .single()

    if (error || !data) {
      return { success: false, message: "Invalid verification code" }
    }

    if (new Date(data.expires_at) < new Date()) {
      await supabase.from("verification_codes").delete().eq("id", data.id)
      return { success: false, message: "Verification code has expired" }
    }

    if (data.attempts >= 3) {
      return { success: false, message: "Too many failed attempts" }
    }

    await supabase.from("verification_codes").delete().eq("id", data.id)

    return { success: true, message: "Code verified successfully" }
  } catch (error) {
    console.error("Error in verifyCode:", error)
    return { success: false, message: "Failed to verify code" }
  }
}
